server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    # ¡LA MAGIA OCURRE AQUÍ!
    # Evita que Nginx use redirecciones absolutas (lo que borraba el puerto 8080)
    # y en su lugar use redirecciones relativas.
    absolute_redirect off;
    port_in_redirect off;
    server_name_in_redirect off;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        
        # Fundamental para aplicaciones estáticas como Astro
        try_files $uri $uri/ /index.html;
    }

    # Redirigir errores de servidor a la página estática
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
